name: ポスターの更新確認・アトラス化

on:
    workflow_dispatch:
    schedule:
        - cron: 37 * * * *

jobs:
    update-posters:
        permissions:
            contents: write
        runs-on: ubuntu-22.04
        outputs:
            updated: ${{ steps.update.outputs.updated }}
        steps:
            - name: メインブランチをチェックアウト
              uses: actions/checkout@v4

            - name: メインブランチへ60日間コミットがないと、スケジュールされたワークフローが停止するのを防止
              # https://docs.github.com/actions/managing-workflow-runs/disabling-and-enabling-a-workflow
              uses: gautamkrishnar/keepalive-workflow@790c7f09285a59b09bb578c85e271c6ff2af97c4 #v1.1.0

            - name: 「posters-data」フォルダへ現在のデータを展開
              id: download-posters-data
              uses: dawidd6/action-download-artifact@e7466d1a7587ed14867642c2ca74b5bcc1e19a2d #v3.0.0
              with:
                name: posters-data
                path: ./posters-data/
                if_no_artifact_found: warn

            - name: FFmpegのインストール
              uses: FedericoCarboni/setup-ffmpeg@36c6454b5a2348e7794ba2d82a21506605921e3d #v3.0.0

            - name: PHPライブラリのキャッシュ
              uses: actions/cache@v3
              env:
                cache-name: cache-php-vendor
              with:
                path: ./vendor
                key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}
                restore-keys: |
                    ${{ runner.os }}-build-${{ env.cache-name }}-
                    ${{ runner.os }}-build-
                    ${{ runner.os }}-

            - name: PHPライブラリのインストール
              run: composer install --no-dev

            - name: 更新
              id: update
              run: composer run-script update-posters
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                GOOGLE_SERVICE_ACCOUNT_SECRET_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_SECRET_KEY }}

            - name: 現在のポスターデータを保持
              if: steps.update.outputs.updated
              uses: actions/upload-artifact@v4
              with:
                name: posters-data
                path: ./posters-data/
                retention-days: 90

            - name: GitHub Pages用のデータをアップロード
              if: steps.update.outputs.updated
              uses: actions/upload-pages-artifact@v3
              with:
                path: _site/

            # v2.xのプレハブで指定しているURL向けに https://github.com/esperecyan/esperecyan.github.io/tree/master を更新
            - name: esperecyan/esperecyan.github.io の master ブランチをチェックアウト
              if: steps.update.outputs.updated
              uses: actions/checkout@v4
              with:
                path: ./esperecyan.github.io
                repository: esperecyan/esperecyan.github.io
                ref: master

            - name: Quest1向け動画をコピー
              if: steps.update.outputs.updated
              run: cp _site/posters-quest1.mp4 esperecyan.github.io/vrchat-posters.mp4

            - name: https://github.com/esperecyan/esperecyan.github.io/tree/master へ GitHub Pages として Commit & Push
              if: steps.update.outputs.updated
              uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
              with:
                deploy_key: ${{ secrets.ESPERECYAN_GITHUB_IO_DEPLOY_KEY }}
                external_repository: esperecyan/esperecyan.github.io
                publish_branch: master
                publish_dir: ./esperecyan.github.io
                force_orphan: true

    deploy:
        needs: update-posters
        if: needs.update-posters.outputs.updated

        permissions:
            pages: write
            id-token: write
        runs-on: ubuntu-22.04
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
