name: ポスターの更新確認・アトラス化

on:
    workflow_dispatch:
    schedule:
        - cron: 37 * * * *

jobs:
    update-posters:
        permissions:
            contents: write
        runs-on: ubuntu-22.04
        steps:
            - name: メインブランチをチェックアウト
              uses: actions/checkout@v3

            - name: 「gh-pages」フォルダへ現在のデータを展開
              uses: actions/checkout@v3
              with:
                path: ./gh-pages
                ref: gh-pages

            - name: FFmpegのインストール
              uses: FedericoCarboni/setup-ffmpeg@102916131ac71e9c7ad6fa9d98fed2c9d86722e6 #v1.1.0

            - name: PHPライブラリのキャッシュ
              uses: actions/cache@v3
              env:
                cache-name: cache-php-vendor
              with:
                path: ./vendor
                key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}
                restore-keys: |
                    ${{ runner.os }}-build-${{ env.cache-name }}-
                    ${{ runner.os }}-build-
                    ${{ runner.os }}-

            - name: PHPライブラリのインストール
              run: composer install --no-dev

            - name: 更新
              run: composer run-script update-posters
              env:
                GOOGLE_SERVICE_ACCOUNT_SECRET_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_SECRET_KEY }}

            - name: コミット
              uses: stefanzweifel/git-auto-commit-action@abd87b7d94702070bef78dc1d56b6928b8fa9ecc #v4.12.0
              with:
                repository: ./gh-pages
                branch: gh-pages
                commit_message: ポスターデータの更新
